# Authors:	João Leitão		 93088
#		  	José Brito		 93106
#  		   	Xavier Fernandes 93202

CC = gcc
CFLAGS = -Wall -Wextra -pedantic -O3 -fopenmp

foxes-rabbits: foxes-rabbits.c
	$(CC) -o $@ $^ $(CFLAGS)

clean:
	rm foxes-rabbits